import Foundation
import SQLite3

// MARK: - DrugDatabase
//
// Read-only SQLite wrapper around the bundled DoseLumaDrugs.sqlite resource.
//
// The database is generated by scripts/build_drug_database.py (run once,
// output committed to the project).  If the file is absent the class
// initialises to nil and all queries return empty results — the app
// continues to function using the barcode-only fallback.
//
// Schema (created by the build script):
//
//   drugs(id, ndc, din, brand_name, generic_name, strength,
//         dosage_form, route, manufacturer)
//   imprints(id, drug_id→drugs.id, imprint, shape, color)
//
// All text columns are stored lowercase for case-insensitive matching.

final class DrugDatabase {
    static let shared = DrugDatabase()

    private var db: OpaquePointer?
    private let dbName = "DoseLumaDrugs.sqlite"

    // MARK: Initialisation

    private init() {
        guard let url = Bundle.main.url(forResource: "DoseLumaDrugs", withExtension: "sqlite") else {
            // Database not yet bundled — silently degrade to barcode-only mode.
            return
        }
        guard sqlite3_open_v2(url.path, &db, SQLITE_OPEN_READONLY, nil) == SQLITE_OK else {
            db = nil
            return
        }
        // Performance pragmas (read-only, memory-mapped)
        exec("PRAGMA journal_mode = OFF")
        exec("PRAGMA cache_size = 2000")
        exec("PRAGMA mmap_size = 268435456")  // 256 MB
    }

    var isAvailable: Bool { db != nil }

    // MARK: Public query API

    /// Look up a drug by its FDA NDC code (accepts NNNNN-NNNN-NN or plain 10-digit).
    func drug(forNDC ndc: String) -> DrugRecord? {
        let normalised = ndc.replacingOccurrences(of: "-", with: "")
        let sql = """
            SELECT brand_name, generic_name, strength, dosage_form, manufacturer, ndc, din
            FROM drugs
            WHERE REPLACE(ndc, '-', '') = ? OR ndc = ?
            LIMIT 1
        """
        return query(sql, args: [normalised, ndc]).first
    }

    /// Look up a drug by its Health Canada DIN (8 digits).
    func drug(forDIN din: String) -> DrugRecord? {
        let sql = """
            SELECT brand_name, generic_name, strength, dosage_form, manufacturer, ndc, din
            FROM drugs WHERE din = ? LIMIT 1
        """
        return query(sql, args: [din]).first
    }

    /// Look up drugs by imprint text, optionally filtered by shape and colour.
    /// Returns up to `limit` results ordered by match specificity.
    func drugs(forImprint imprint: String,
               shape: String? = nil,
               color: String? = nil,
               limit: Int = 5) -> [DrugRecord] {
        // Exact imprint match first, then fuzzy (LIKE)
        var sql = """
            SELECT d.brand_name, d.generic_name, d.strength, d.dosage_form,
                   d.manufacturer, d.ndc, d.din
            FROM imprints i
            JOIN drugs d ON d.id = i.drug_id
            WHERE i.imprint = ?
        """
        var args: [String] = [imprint.lowercased()]

        if let shape = shape {
            sql += " AND i.shape = ?"
            args.append(shape.lowercased())
        }
        if let color = color {
            sql += " AND i.color = ?"
            args.append(color.lowercased())
        }
        sql += " LIMIT \(limit)"

        var results = query(sql, args: args)

        // If exact match found nothing, try partial imprint (starts-with)
        if results.isEmpty {
            var fuzzSQL = """
                SELECT d.brand_name, d.generic_name, d.strength, d.dosage_form,
                       d.manufacturer, d.ndc, d.din
                FROM imprints i
                JOIN drugs d ON d.id = i.drug_id
                WHERE i.imprint LIKE ?
            """
            var fuzzArgs: [String] = ["\(imprint.lowercased())%"]
            if let shape = shape { fuzzSQL += " AND i.shape = ?"; fuzzArgs.append(shape.lowercased()) }
            if let color = color { fuzzSQL += " AND i.color = ?"; fuzzArgs.append(color.lowercased()) }
            fuzzSQL += " LIMIT \(limit)"
            results = query(fuzzSQL, args: fuzzArgs)
        }
        return results
    }

    // MARK: Private helpers

    private func query(_ sql: String, args: [String]) -> [DrugRecord] {
        guard let db else { return [] }
        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &stmt, nil) == SQLITE_OK else { return [] }
        defer { sqlite3_finalize(stmt) }

        for (i, arg) in args.enumerated() {
            sqlite3_bind_text(stmt, Int32(i + 1), (arg as NSString).utf8String, -1, nil)
        }

        var records = [DrugRecord]()
        while sqlite3_step(stmt) == SQLITE_ROW {
            func col(_ i: Int32) -> String? {
                guard let raw = sqlite3_column_text(stmt, i) else { return nil }
                return String(cString: raw)
            }
            records.append(DrugRecord(
                brandName:    col(0) ?? "",
                genericName:  col(1),
                strength:     col(2),
                dosageForm:   col(3),
                manufacturer: col(4),
                ndc:          col(5),
                din:          col(6)
            ))
        }
        return records
    }

    @discardableResult
    private func exec(_ sql: String) -> Bool {
        guard let db else { return false }
        return sqlite3_exec(db, sql, nil, nil, nil) == SQLITE_OK
    }
}

// MARK: - DrugRecord

struct DrugRecord: Sendable {
    let brandName:    String
    let genericName:  String?
    let strength:     String?
    let dosageForm:   String?
    let manufacturer: String?
    let ndc:          String?
    let din:          String?

    /// Convert to a MedicationMatch for display in PillScannerView.
    func toMatch(confidence: Double, source: MedicationMatch.MatchSource) -> MedicationMatch {
        MedicationMatch(
            drugName:     brandName,
            genericName:  genericName,
            strength:     strength,
            ndc:          ndc,
            din:          din,
            manufacturer: manufacturer,
            confidence:   confidence,
            matchSource:  source
        )
    }
}
